version: 2
jobs:
  "build-dev":
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Pull down Master Script 2
          command: git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
      - run:
          name: Add env vars
          command: |
            echo export TEST_VAR_01="This is VAR1" >> "$BASH_ENV"
            echo export TEST_VAR_02="This is VAR2" >> "$BASH_ENV"
      - checkout
      - run:
          name: Install tools
          command: |
            sudo apt-get update; sudo apt-get install python-dev -y
            sudo curl https://bootstrap.pypa.io/get-pip.py -o -|sudo python
            pip install awscli --upgrade --user
      - setup_remote_docker
      - run:
          name: Check env vars
          command: |
            echo $TEST_VAR_01
            echo $TEST_VAR_02
      - run:
          name: Build Docker image
          command: ./buildECSDockerImage.sh DEV
      - deploy:
          name: Deploy application
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
            cp ./../buildscript/master_deply_v4.2.sh .
            ./master_deply_v4.2.sh -d ECS -e DEV -t $CIRCLE_SHA1 -s oauth_test_app
workflows:
  version: 2
  build:
    jobs:
      - "build-dev":
          filters:
            branches:
              only:
                - dev
