version: 2
jobs:
  "build-dev":
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Run NPM install
          command: npm i
workflows:
  version: 2
  build:
    jobs:
      - "build-dev"
