version: 2
jobs:
  "build-dev":
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: Pull down Master Script 2
          command: git clone --branch master https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript$
      - checkout
      - run:
          name: Run NPM install
          command: npm i
      - deploy:
          name: Deploy application
          command: |
            cp ./../buildscript/master_deply_v4.2.sh .
            ./master_deply_v4.2.sh -e DEV -t $CIRCLE_SHA1 -s oauth_test_app
workflows:
  version: 2
  build:
    jobs:
      - "build-dev":
          filters:
            branches:
              only:
                - dev
